### ISSUE TITLE
Attribute Error While Dragging Segments

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphas#222]
**Describe the bug**
A reproducible bug, but takes work to make it happen.
```
Traceback (most recent call last):
  File "/home/dan/Projects/gaphor/.venv/lib/python3.9/site-packages/gaphas/segment.py", line 213, in on_drag_update
    segment_state.moving.move((x + offset_x, y + offset_y))
AttributeError: 'NoneType' object has no attribute 'move'
```

**To Reproduce**
1. Create two classes
2. Create a generalization between them
3. Set the relationship to Rectilinear
4. Drag the relationship around, create segments, and connect and disconnect the ends.

**Expected behavior**
No AttributeError

**Screenshots**

**OS**
- [X] Linux (Please put in notes the specific distro)
- [ ] MacOS
- [ ] Windows

NOTES:

**Version**
Version of Gaphas: 3.0.1

**Additional context**
Maybe we just need to check for `moving`?

```
if segment_state.moving: 
    segment_state.moving.move((x + offset_x, y + offset_y))
```

**Comment by amolenaar** [comment]
Fixed in e432890.
