### ISSUE TITLE
Wrong access to scroll event

### ISSUE THREAD

**Issue by franzlst** [gaphor/gaphas#23]
The scroll event in [`on_scoll`](https://github.com/gaphor/gaphas/blob/7e4c8a250c55f617f90905c04057ee1d8b7ce1d7/gaphas/tool.py#L594) needs to be accessed correctly:
* `event.x` => `event.get_coords()[1]`
* `event.y` => `event.get_coords()[2]`
* `event.direction` => `event.get_scroll_direction()[1]`

**Comment by danyeaw** [comment]
@franzlst Thanks for testing and submitting the issues :+1:. Would be interested in submitting a PR as well?

**Comment by franzlst** [comment]
Here your are: pull request #24 :smile: 

BTW: We are making good progress in porting [RAFCON](https://github.com/DLR-RM/RAFCON/) to Python 3 and Gtk+ 3. Stay tuned!

**Comment by danyeaw** [comment]
@franzlst Great to hear!
