### ISSUE TITLE
Improve render speed

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphas#234]
## Is your feature request related to a problem?

Currently, when implementing `Item.draw()`, you have to take into account speed: every time a canvas is redrawn, this method is called.

Rendering is relatively slow, esp. on macOS. 

I did some trails with `cairo.RecordingSurface`, but that's probably not what we need: to render a surface it has to be applied as a _pattern_ on the target surface. For our purposes it would be enough to just replay any drawing operation on the target surface. My assumption is that that will also be faster.

## Describe the solution you'd like

When an item is drawn (the first time this happens is when the bounding box is calculated), the drawing operations should be recorded. On subsequent draws, the recorded items should be replayed. This ensures that:
1. we always draw the same thing, until the item requires an update (keeps bounding box consistent)
2. the concern of `draw()` being fast is less strict

Solution to be determined still. See alternatives.

## Describe alternatives you've considered

* Create a custom DrawingContext for Gaphas. Instead of calling DrawingContext.cairo methods, expose all required methods through DrawingContext directly. This should also expose methods for rendering Pango Layouts and SVG images (librsvg).
* Use `RecordingSurface`. For one, @danyeaw  got artifacts in the diagram. Secondly it's applied via patterns, where it's more logical for us to just just replay the recorded events on a surface. 
* Maybe add a bit of C/Cython) code that hooks into cairo and provides the required capabilities (e.g. expose RecordingSurface.replay or expose the surface observer code).

## Additional context

We should handle SVG and Pango layouts as well. They render to a `cairo.Context` directly. Do we want to keep that interface, or provide a Gaphas specific way to render those?

**Comment by amolenaar** [comment]
I created a little performance test. It's drawing 5 boxes, each box drawing 20 rectanges.

## `performance` -- shows the performance of the current implementation
```
Testing 5 boxes for 200 rounds
update: 3939.463 ms
bounding box: 1653.080 ms
update back buffer: 2031.183 ms
draw: 13.321 ms
```

## `perf/bounding-box-context` -- The old style bounding box calculator

```
Testing 5 boxes for 200 rounds
update: 5232.414 ms
bounding box: 2943.602 ms
update back buffer: 2032.779 ms
draw: 13.372 ms
```

## `perf/recording` -- Use `cairo.RecordingSurface`

```
Testing 5 boxes for 200 rounds
update: 4010.482 ms
bounding box: 1685.509 ms
update back buffer: 2043.602 ms
draw: 12.810 ms
```

## Conclusion

The updates to bounding box calculation really pay of. Oddly enough, the recording does not save a lot of time updating the back buffer.

**Comment by danyeaw** [comment]
@amolenaar Very impressive speedups!

**Comment by amolenaar** [comment]
@danyeaw I would like to see some improvements on the back-buffer update. Currently the items is rendered twice: once for it's bounding box and once for the real drawing. It would be nice if we can reduce it, so an item has to be drawn only once.

Currenlty that's not possible: when drawing the back-buffer we invoke other painters, alongside the item painter. In the "bounding box" phase we call the item-painter only.

**Comment by amolenaar** [comment]
Won some speed by increasing the tolerance for boundbox drawing.
