### ISSUE TITLE
Missing reference to minimum size constraints in Element

### ISSUE THREAD

**Issue by franzlst** [gaphor/gaphas#25]
In cdf08dffbe3a38f0880e1d3b5b616388042143bf, minimum size constraints for `Element`s were introduced and stored in `self._c_min_w` and `self._c_min_w`. In 2ca1e2e84f63c505dabc15aec6dd20eddae866ca, those two references were removed. As a consequence, those constraints can no longer be accessed directly, but need to be searched for in the list of all constraints `self._constraints`. So the latest `0.7.2` release contains the references, but no longer the latest `master` version.

Is there are reason for this or can those references be added again?

**Comment by danyeaw** [comment]
@franzlst Thanks for the report. @amolenaar do you have any background on these changes?

**Comment by franzlst** [comment]
In RAFCON, I sometimes need to solve single constraints instead of all for performance reasons. This is the case when doing a recursive resize of states and their children, see [this code](https://github.com/DLR-RM/RAFCON/blob/9664c8de0dd565a6c2d9695f4dcec08c38f83ea2/source/rafcon/gui/mygaphas/items/state.py#L885).

I found a simple workaround for the missing references, so this is not a big deal for me any longer:
```python
# In the __init__ before more constraints are added
self._c_min_w = self._constraints[0]
self._c_min_h = self._constraints[1]
```

**Comment by amolenaar** [comment]
👍
