### ISSUE TITLE
Check setup.py requirements

### ISSUE THREAD

**Issue by franzlst** [gaphor/gaphas#32]
Could you please have a look at the requirements in your `setup.py`?

* `setup_requires` contains:
  * `pytest-*` packages, which I guess can be moved to `tests_require`
  * `six`is this required? You use `futurize`
  * `pre-commit`: Required for installation?
* `install_requires`
  * `PyGObject >= 3.26.1`: Is PyGObject really required in this version? We use it with PyGObject 3.20, so this could be a minimum version
  * `pycairo >= 1.11.0`: Is pycairo really required in this version? We use it with pycairo 1.10, so this could be a minimum version

**Comment by danyeaw** [comment]
In #33:

- I made pytest-* only install if pytest is run
- six is being used in the state module to determine whether it is being run from Python2 or 3
- added pre-commit to requirements.txt only
- Relaxed the install requirements for PyGObject and pycairo as you suggested

Please let me know if you have any more feedback.

**Comment by franzlst** [comment]
Thanks for taking care of this!

If you want to save a further dependency, you could still remove `six` and check the Python version using `sys.version_info[0]`.

**Comment by danyeaw** [comment]
@franzlst Good point, I have removed six as an install dependency. It is still a dev dependency because many of the dev packages depend on it.
