### ISSUE TITLE
gaphas gtk3 with python 3 supports still python 2.7.x

### ISSUE THREAD

**Issue by Rbelder** [gaphor/gaphas#38]
If you plan to support python 2.7 and python 3.4 and higher you have to keep your tests running under python 2.7, too. In your .travis.yml file you label 2.7 and 3.5, 3.6, 3.7 to be supported.

At the moment your code got some lines that can not be executed by python 2.7.13 which we still use in our RAFCON environments in our institute.
So currently the last good commit is f1bbb9dc. Thereby problems start with the use of `super` calls that are not valid to python 2.7 like `super()`.

RAFCON aims to support python 2.7 without gtk3 and 2.7 and 3.4 (current version in our labs), 3.5, 3.6, 3.7 with gtk3, for now.

Note:
Sorry if the description sounds a bit pushy. This was not my intention.

**Comment by danyeaw** [comment]
@Rbelder Thanks for submitting the issue. My intention was to support 2.7, 3.5, 3.6, and 3.7. It isn't quite clear for me from your description what you are requesting.

Would you like me to continue to support 3.4?

When you say you are supporting 2.7 without gtk3, does that mean you are going to stay on the 0.7.2 version for that use case?

What portions of the code on master aren't compatible with 2.7? Python 2.7 [supports super()](https://docs.python.org/2.7/library/functions.html#super), and all tests are passing with 2.7.15 locally using tox and in Travis. Is the issue related to your use of 2.7.13?

**Comment by Rbelder** [comment]
> When you say you are supporting 2.7 without gtk3, does that mean you are going to stay on the 0.7.2 version for that use case?

Concerning this we will stay on the release 0.7.2.

I wanted to enforce python 2.7 support. I have not estimated that there could be differences on patch level. So I really mean the super() without self argument. What is not supported by respective python version.

But I discovered that I was on a intermediate pull of the master not on the latest (from today (so forgot to pull ones more). Sorry for the inconvenience. You have fixed this issue later on in your code. I thought the master will be stable any time I pull. I close the issue.

Note: In our project we use the master for releases and develop to merge features and keep both as stable as possible. I know that your project is different but I have not re-thought this before creating the issue.

**Comment by Rbelder** [comment]
One more comment on the constellation supporting 2.7 without gtk3 which is obsolete on a stable 0.13 patch level.

The idea was limited support of critical issues and easy portable minor issues for a minimum time horizon because minor 0.13 is not released yet and we have to wait if there are critical issues because of the gtk3/python3 refactoring which are not known yet and thus need patch releases.

From our site we hope to do only one more patch on 0.12 and continue then only with 0.13 which supports python 2 and 3.
