### ISSUE TITLE
Replace use of `simplegeneric` with `functools.singledispatch`

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphas#46]
As of Python 3.4 (I think), a generic function implementation is part of the Python standard libs. We should take advantage of this.

Q: How does this impact Python 2.7 support? Is it provided through `future`?
Q: Can we add https://pypi.org/project/singledispatch/ as a Python2 only dependency?

See also: https://www.python.org/dev/peps/pep-0443/

**Comment by danyeaw** [comment]
According to the [future standard library import page](https://python-future.org/standard_library_imports.html) it is available using the pip install version only.

Setuptools allows adding [platform / version dependencies](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies).
Pyproject.toml allows adding it [as well](https://flit.readthedocs.io/en/latest/pyproject_toml.html) like so:

```
requires = [
    "requests >=2.6",
    "configparser; python_version == '2.7'",
]
```
