### ISSUE TITLE
Wrong minimum version of pycairo

### ISSUE THREAD

**Issue by franzlst** [gaphor/gaphas#56]
You specify `pycairo` 1.11.0 as minimum version. However, you now use `Cairo.COLOR`, which has (according to https://pycairo.readthedocs.io/en/latest/reference/enums.html#cairo.Content) been introduced with not before version 1.13

**Comment by danyeaw** [comment]
Thanks so much for the bug reports @franzlst :tada:

**Comment by franzlst** [comment]
Thx for fixing!
