### ISSUE TITLE
Background color should be configurable

### ISSUE THREAD

**Issue by franzlst** [gaphor/gaphas#57]
With the new back-buffer, `gaphas` hard codes the background color of the canvas to be white ([here](https://github.com/gaphor/gaphas/blob/master/gaphas/view.py#L791) and I think also [here](https://github.com/gaphor/gaphas/blob/master/gaphas/view.py#L863)).

This value should be configurable.

**Comment by franzlst** [comment]
Maybe it is also possible to make it transparent, so that the beneath widget color is visible. This would also be more backward compatible/require less adaptions for other projects :-)

**Comment by amolenaar** [comment]
You're right. I took a while to figure out how to set the default color to transparent, but in the end the result is pretty nice.

We could also use the GTK theming stuff to draw a background if you want, but I assume this is good enough for now.

**Comment by franzlst** [comment]
Thank you!
