### ISSUE TITLE
Back buffer: Only draw items in view

### ISSUE THREAD

**Issue by franzlst** [gaphor/gaphas#64]
When creating the back buffer, [gaphas draws all itmes](https://github.com/gaphor/gaphas/blob/master/gaphas/view.py#L404). Wouldn't it be easy to first determine, which items are visible (e.g. using [get_items_in_rectangle](https://github.com/gaphor/gaphas/blob/master/gaphas/view.py#L335)) and only pass these items to the painter?

**Comment by amolenaar** [comment]
You're absolutely right. This is a small optimization.

**Comment by franzlst** [comment]
Thank you!
