### ISSUE TITLE
Add requirements.txt 

### ISSUE THREAD

**Issue by RodionovGV** [gaphor/gaphas#67]
Please, add requirements.txt.

**Comment by amolenaar** [comment]
Hi,

All dependencies are listed in the [`pyproject.toml` file](https://medium.com/@grassfedcode/pep-517-and-518-in-plain-english-47208ca8b7a6). Why duplicate them in a `requirements.txt` file? The build tool of choice is [Poetry](https://poetry.eustace.io), which depends fully on the new `pyproject.toml` format. For distribution, wheel packages are build which will install just fine using Pip.

**Comment by danyeaw** [comment]
@RodionovGV Thanks for submitting the issue. It would be good if you explained why you think you need this so we could understand your use case.

As @amolenaar said, [PEP518](https://www.python.org/dev/peps/pep-0518/) is the new modern way to identify requirements for a Python project, and the pyproject.toml replaces requirements.txt, setup.py, setup.cfg, and other configuration files. If for some reason you do need a requirements.txt file you can follow the instructions in the README to setup a development environment and then type `pip freeze > requirements.txt`.
