### ISSUE TITLE
Is gaphas accepting new contributions and pull requests?

### ISSUE THREAD

**Issue by jlstevens** [gaphor/gaphas#7]
First, I wish to thank you for your work on gaphas!

Gaphas has been a real delight to use. The code is of excellent quality, very readable and well documented. I love that gaphas has minimal dependencies, is written in pure Python and successfully abstracts away the more painful parts of using a `gtk.DrawingArea` as a canvas. Gaphas is quite wonderful,  thank you!

I've been working on a prototype project using gaphas to implement  something like the [Blender node editor](http://wiki.blender.org/uploads/a/a1/Manual-Part-IV-Texture-Node-Example.png). This project is currently in a private repository but I hope to make it public very soon. 

My main concern with gaphas is that the last public commit is from July 2012. Is development still active? Are you accepting pull requests? While learning gaphas, I have made several improvements that I would like to contribute back. Some suggestions that I would be happy to submit as a series of pull requests:
- Multiple typo fixes.
- Deletion of trailing whitespace.
- Possible addition of a `.gitignore` to the gaphas repository.
- Deletion of code that has been commented out (only a few instances of this).
- Wrapping docstrings to 80 characters (mostly good already, but a few places could do with better wrapping).
- A few other more technical ideas if you are interested!

Please do tell me if you are interested in accepting these sorts of PRs!

**Comment by danyeaw** [comment]
Gaphas is active again, I will be maintaining the project. We are working on porting it to [toga](https://github.com/pybee/toga) to make it truly cross platform native.

**Comment by franzlst** [comment]
Hi @danyeaw, 

it is great to hear that gaphas is active again!

You ported gaphas to Gtk3 and I guess it no longer supports Gtk2? Would it be possible to have separate branches for Gtk2 and Gtk3 and at least fix bugs in both branches (such as my pull request #13)?

Keep up the good work!

**Comment by danyeaw** [comment]
Hi @franzlst, I may be open to keeping branches, but I would really like to focus on migrating to Toga. How great would a truly cross platform native GUI be!

Are you currently using gaphas for another app? I would like to understand current usage before committing to supporting pygtk long term. Pygtk is no longer maintained, last update was in 2011. Legacy python is also on its (death march)[https://pythonclock.org/].

**Comment by franzlst** [comment]
> Hi @franzlst, I may be open to keeping branches, but I would really like to focus on migrating to Toga. How great would a truly cross platform native GUI be!

Sure! But cherry-picking bugfix commits would be great nevertheless.Migrating a project from GTK 2 to 3 is not an easy task, so this would help people that are currently using gaphas.

We use gaphas for RAFCON, a tool for the visual programming hierarchical state machines. You can read about it in [this paper](http://elib.dlr.de/109245/) or watch [this video](https://www.youtube.com/watch?v=35dUykJandU). We plan to make this tool open source within the next months.

**Comment by jlstevens** [comment]
@franzlst 

That is quite funny! I was using gaphas for essentially the same task for a personal/side-project I was working on. 

I also used gaphas to visually connect between computational components drawn on a canvas for working in a dataflow programming style. I eventually stopped using gaphas when I switched from Linux to a macbook  (given to me by my employer - I miss Linux!) which made it much harder to use GTK.

This project (currently unmaintained) became [boxflow](https://github.com/ioam/boxflow), using HTML5 canvas. I think it is worth mentioning all this in case there is an opportunity here to avoid more reinvention of the wheel.  A generic library based on gaphas for writing dataflow style applications would be a nice thing to have!

**Comment by danyeaw** [comment]
@franzlst Thanks for sharing, that's a very cool use of gaphas! I will do my best to keep the master branch a 0.17.x version that supports gtk2 with bugfixes. When the switch to Toga is ready, it will be a breaking change to the API and we'll release a new major version as 1.x.x.

@amolenaar also mentioned to me that [ASCEND](http://ascend4.org) is using the library as well. Maybe we could start a list the documentation of the different uses of the library.
