### ISSUE TITLE
Version 2.1 API Changed for draw method

### ISSUE THREAD

**Issue by danyeaw** [gaphor/gaphas#77]
In gaphor/gaphas#73 we removed the draw_all property from the draw method, which version 1.2.0 of Gaphor depends on. This Gaphor issue is https://github.com/gaphor/gaphor/issues/359.

I recommend we release a new version that is backwards compatible, and then release version 3.0 with a change of the API if we think this cleanup is needed.

**Comment by amolenaar** [comment]
Nice find! I had not anticipated this issue to pop up.
